name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Run bats tests
      run: ./tests/bats/bin/bats tests/test_executable.bats
